version: "3"

services:

    rest-service:
        env_file: .env
        container_name: rest-service
        build:
          context: .
          dockerfile: Dockerfile
          args:
            ENV_FILE: .env
            BASE_DIR: /h-rest
        # Migrating the database in the command where the server is runned is dangerous but
        # in this case simplifies execution
        command:  flask run -h 0.0.0.0 -p 5000
        volumes:
          - .:/h-rest
        ports:
          - "5000:5000"
