version: "3"

services:

    rest-service:
        env_file: .env
        container_name: rest-service
        build:
          context: .
            dockerfile: Dockerfile
            args:
              ENV_FILE: .env
              BASE_DIR: /h-rest
        command:  /command.sh
        volumes:
          - .:/h-rest
        # ports:
        #   - "5000:5000"

    nginx-rest-service:
      image: rest-service-nginx
      build:
          context: nginx
          dockerfile: Dockerfile
          args:
            ENV_FILE: .env
            BASE_DIR: /flask-jwt-auth
      container_name: rest-service-nginx
      restart: always
      ports:
        - "80:80"
      depends_on:
        - rest-service